/**
 * @file auto-optimizer.ts — 全自动优化编排器 (Phase 5)
 * @description
 *   Self-Optimization 子系统的 Phase 5 核心组件，负责串联整个自动优化流程：
 *
 *   1. 自我审视 (Inspection) → 分析代码质量、架构完整性、痛点
 *   2. 外部调研 (Research) → 搜索先进的架构模式和最佳实践
 *   3. 生成提案 (Proposal) → 基于痛点和调研生成优化方案
 *   4. Git 快照 (Snapshot) → 在变更前创建 Git 快照，用于回滚
 *   5. 执行优化 (Execution) → 应用文件变更，运行测试
 *   6. 自动修复 (Auto-fix) → 如果测试失败，调用 LLM 生成修复补丁
 *   7. 回滚 (Rollback) → 如果修复失败，回滚到 Git 快照
 *   8. 记录日志 (Logging) → 将结果写入 OPTIMIZATION_LOG.md
 *
 *   执行策略：
 *   - 低风险 (low) 提案：自动执行
 *   - 中风险 (medium) 提案：跳过（需要用户确认）
 *   - 高风险 (high/destructive) 提案：跳过（必须手动审核）
 *
 *   安全机制：
 *   - Git 快照：执行前创建，成功则 finalize，失败则 revert
 *   - 测试验证：每次变更后运行测试，确保不破坏现有功能
 *   - 自动修复上限：最多 2 次修复尝试（防死循环）
 *
 * @module core/self-opt/auto-optimizer
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type {
  InspectionReport,
  ResearchReport,
  OptimizationProposal,
  OptimizationResult,
  OptimizationLogEntry,
  FileChange,
} from "./types.js";
import { generateProposals, generateFileChanges } from "./proposal-engine.js";
import { executeOptimization } from "./self-test-runner.js";
import {
  createSnapshot,
  revertToSnapshot,
  finalizeSnapshot,
  isInGitRepo,
} from "./git-snapshot.js";
import { generateFixDiff } from "./diff-generator.js";

// ============================================================================
// 配置
// ============================================================================

/** 允许自动执行的风险等级（仅低风险） */
const AUTO_RISK = ["low"] as const;

// ============================================================================
// 优化日志管理
// ============================================================================

/**
 * 加载优化历史日志
 *
 * 从 OPTIMIZATION_LOG.md 中解析所有 JSON 记录，
 * 用于分析优化历史和趋势。
 *
 * @param projectRoot 项目根目录
 * @returns 优化日志条目列表
 *
 * @example
 * ```ts
 * const logs = loadOptimizationLog(projectRoot);
 * console.log(`共 ${logs.length} 次优化记录`);
 * ```
 */
export function loadOptimizationLog(
  projectRoot: string
): OptimizationLogEntry[] {
  const logPath = path.join(projectRoot, "OPTIMIZATION_LOG.md");
  if (!fs.existsSync(logPath)) return [];

  try {
    const content = fs.readFileSync(logPath, "utf-8");
    // 提取所有 JSON 代码块
    const blocks = content.match(/\{[\s\S]*?\}/g);
    if (!blocks) return [];

    const entries: OptimizationLogEntry[] = [];
    for (const b of blocks) {
      try {
        const e = JSON.parse(b);
        if (e.result && e.proposal) entries.push(e);
      } catch {
        // 忽略解析失败的块
      }
    }
    return entries;
  } catch {
    return [];
  }
}

/**
 * 追加优化日志记录
 *
 * 将单次优化的结果追加到 OPTIMIZATION_LOG.md 文件中。
 * 如果文件不存在，会自动创建并添加标题。
 *
 * @param projectRoot 项目根目录
 * @param entry 优化日志条目
 *
 * @example
 * ```ts
 * appendOptimizationLog(projectRoot, {
 *   result: optimizationResult,
 *   proposal: { id: "prop-1", type: "add", target: "测试", ... }
 * });
 * ```
 */
export function appendOptimizationLog(
  projectRoot: string,
  entry: OptimizationLogEntry
): void {
  const logPath = path.join(projectRoot, "OPTIMIZATION_LOG.md");
  const record = `## ${new Date().toISOString()}\n\n\`\`\`json\n${JSON.stringify(
    entry,
    null,
    2
  )}\n\`\`\`\n\n---\n\n`;

  if (!fs.existsSync(logPath)) {
    // 创建新文件，添加标题
    fs.writeFileSync(
      logPath,
      `# Optimization Log\n\n> Auto-generated by Mini Agent Self-Optimization System\n\n---\n\n${record}`,
      "utf-8"
    );
  } else {
    // 追加到现有文件
    fs.appendFileSync(logPath, record, "utf-8");
  }
}

// ============================================================================
// 内部类型
// ============================================================================

/**
 * 单个提案执行结果
 *
 * 包含提案、优化结果、Git 快照哈希和回滚状态。
 */
interface ExecResult {
  /** 优化提案 */
  proposal: OptimizationProposal;
  /** 优化执行结果 */
  result: OptimizationResult;
  /** Git 快照哈希（执行前） */
  gitSnapshot?: string;
  /** 是否已回滚 */
  reverted: boolean;
}

// ============================================================================
// 内部辅助函数
// ============================================================================

/**
 * 应用文件变更到磁盘
 *
 * 根据 FileChange[] 创建、修改或删除文件。
 * 会自动创建不存在的父目录。
 *
 * @param changes 文件变更列表
 * @param cwd 工作目录（项目根目录）
 * @returns 操作结果
 */
async function applyChanges(
  changes: FileChange[],
  cwd: string
): Promise<{ success: boolean; error?: string }> {
  try {
    for (const f of changes) {
      const full = path.isAbsolute(f.path) ? f.path : path.join(cwd, f.path);

      if (f.action === "create" || f.action === "modify") {
        // 创建父目录（如果不存在）
        const dir = path.dirname(full);
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }
        // 写入文件内容
        if (f.content) {
          fs.writeFileSync(full, f.content, "utf-8");
        }
      } else if (f.action === "delete" && fs.existsSync(full)) {
        // 删除文件
        fs.unlinkSync(full);
      }
    }
    return { success: true };
  } catch (e: any) {
    return { success: false, error: e?.message };
  }
}

/**
 * 执行单个优化提案
 *
 * 工作流程：
 * 1. 创建 Git 快照（用于回滚）
 * 2. 确保有文件变更（如果没有，调用 generateFileChanges 或 diff-generator）
 * 3. 应用文件变更
 * 4. 运行测试
 * 5. 如果测试失败，尝试自动修复（由 executeOptimization 处理）
 * 6. 如果成功，finalize Git 快照；如果失败，回滚
 *
 * @param p 优化提案
 * @param cwd 项目根目录
 * @param srcDir 源码目录
 * @param useGit 是否使用 Git 快照
 * @returns 执行结果
 */
async function execProposal(
  p: OptimizationProposal,
  cwd: string,
  srcDir: string,
  useGit: boolean
): Promise<ExecResult> {
  let snap: string | null = null;

  // ── Step 1: 创建 Git 快照 ──
  if (useGit) {
    console.log(`  📸 创建快照: ${p.target}`);
    snap = await createSnapshot(cwd, `pre-${p.target}`);
    if (snap) console.log(`  📸 ${snap.slice(0, 8)}`);
  }

  // ── Step 2: 确保有文件变更 ──
  if (p.files.length === 0) {
    // 方法 1: 调用 generateFileChanges 基于模板生成
    const { inspectSelf } = await import("./inspector.js");
    const insp = await inspectSelf(srcDir);
    generateFileChanges(p, insp);

    // 方法 2: 如果还是没有，用 diff-generator 生成
    if (p.files.length === 0) {
      const fake = p.testCases.map((tc) => ({
        testCaseId: tc.id,
        passed: false,
        output: "待生成",
        durationMs: 0,
      }));
      const diff = await generateFixDiff(p, fake, srcDir);
      if (diff.success) p.files = diff.changes;
    }
  }

  // ── Step 3: 执行优化（含测试和自动修复） ──
  const result = await executeOptimization(p, cwd, async () =>
    applyChanges(p.files, cwd)
  );

  // ── Step 4: 处理 Git 快照 ──
  if (useGit && snap) {
    if (result.status === "success") {
      // 成功：finalize 快照（修改 commit message）
      await finalizeSnapshot(cwd, snap, `[self-opt] ${p.target}`);
    } else {
      // 失败：回滚到快照
      const rv = await revertToSnapshot(cwd, snap);
      result.reverted = rv.success;
      if (rv.success) {
        result.lesson += " [已回滚]";
      } else {
        result.lesson += ` [回滚失败: ${rv.error}]`;
      }
    }
  }

  return {
    proposal: p,
    result,
    gitSnapshot: snap ?? undefined,
    reverted: result.reverted,
  };
}

// ============================================================================
// 主入口：全自动优化
// ============================================================================

/**
 * 自动优化结果接口
 */
export interface AutoOptimizeResult {
  /** 自我审视报告 */
  inspection: InspectionReport;
  /** 外部调研报告 */
  research: ResearchReport;
  /** 所有生成的提案 */
  proposals: OptimizationProposal[];
  /** 已执行的提案及结果 */
  executed: ExecResult[];
  /** 跳过的提案（中高风险） */
  skipped: OptimizationProposal[];
  /** 执行摘要 */
  summary: string;
}

/**
 * 全自动优化主函数
 *
 * 这是 `.optimize auto` 命令的入口点，串联整个优化流程：
 *
 * ```
 * [1/5] 自我审视 → Inspector 分析代码质量
 * [2/5] 外部调研 → Researcher 搜索最佳实践
 * [3/5] 生成提案 → ProposalEngine 生成优化方案
 * [4/N] 执行提案 → 应用变更 + 测试 + 自动修复 + Git 快照
 * [5/5] 输出报告 → 格式化结果
 * ```
 *
 * @param srcDir 项目 src/ 目录路径
 * @param projectRoot 项目根目录
 * @returns 自动优化结果
 *
 * @example
 * ```ts
 * const projectRoot = process.cwd();
 * const srcDir = path.join(projectRoot, "src");
 * const result = await autoOptimize(srcDir, projectRoot);
 * console.log(result.summary);
 * // 输出: "执行 1，成功 1，失败 0，回滚 0"
 * ```
 */
export async function autoOptimize(
  srcDir: string,
  projectRoot: string
): Promise<AutoOptimizeResult> {
  // ── Step 1: 自我审视 ──
  console.log("\n[1/5] 🔍 自我审视...");
  const { inspectSelf } = await import("./inspector.js");
  const insp = await inspectSelf(srcDir);
  console.log(
    `  架构: ${
      insp.architectureChecks.filter((c) => c.passed).length
    }/${insp.architectureChecks.length}`
  );
  console.log(
    `  未测试模块: ${
      insp.moduleAnalysis.filter((m) => !m.hasTests && m.linesOfCode > 50)
        .length
    } 个`
  );

  // ── Step 2: 外部调研 ──
  console.log("\n[2/5] 🌐 外部调研...");
  const { researchExternal } = await import("./researcher.js");
  const res = await researchExternal();
  console.log(`  资源: ${res.references.length} 个`);

  // ── Step 3: 生成提案 ──
  console.log("\n[3/5] 📋 生成提案...");
  const proposals = generateProposals(insp, res);
  // 为每个提案生成文件变更
  for (const p of proposals) {
    generateFileChanges(p, insp);
  }

  // 分类：自动执行 vs 跳过
  const auto = proposals.filter((p) =>
    AUTO_RISK.includes(p.riskLevel as "low")
  );
  const skipped = proposals.filter(
    (p) => !AUTO_RISK.includes(p.riskLevel as "low")
  );
  console.log(
    `  总计: ${proposals.length}, 自动: ${auto.length}, 跳过: ${skipped.length}`
  );

  // ── Step 4: 执行提案 ──
  const useGit = await isInGitRepo(projectRoot);
  const executed: ExecResult[] = [];

  for (let i = 0; i < auto.length; i++) {
    console.log(
      `\n[4/${auto.length}] 📌 执行: ${auto[i].target} (${auto[i].files.length} 文件变更)`
    );

    const r = await execProposal(auto[i], projectRoot, srcDir, useGit);
    executed.push(r);

    // 记录到日志
    appendOptimizationLog(projectRoot, {
      result: r.result,
      proposal: {
        id: r.proposal.id,
        type: r.proposal.type,
        target: r.proposal.target,
        description: r.proposal.description,
        riskLevel: r.proposal.riskLevel,
      },
    });

    console.log(
      `  ${r.result.status === "success" ? "✅" : "❌"} ${r.result.lesson}`
    );
    if (r.gitSnapshot) {
      console.log(`  📸 快照: ${r.gitSnapshot.slice(0, 8)}`);
    }
  }

  // ── Step 5: 生成摘要 ──
  const ok = executed.filter((e) => e.result.status === "success").length;
  const fail = executed.filter((e) => e.result.status === "failed").length;
  const rv = executed.filter((e) => e.result.reverted).length;
  const summary =
    `执行 ${executed.length}，成功 ${ok}，失败 ${fail}，回滚 ${rv}` +
    (skipped.length > 0 ? `，${skipped.length} 个跳过` : "");

  return {
    inspection: insp,
    research: res,
    proposals,
    executed,
    skipped,
    summary,
  };
}

// ============================================================================
// 格式化输出
// ============================================================================

/**
 * 将自动优化结果格式化为可读文本
 *
 * 用于 CLI 展示，包含：
 * - 执行摘要（总数、成功、失败、回滚）
 * - 每个已执行提案的结果（测试通过数、快照哈希）
 * - 跳过的提案列表
 *
 * @param r 自动优化结果
 * @returns 格式化的文本字符串
 *
 * @example
 * ```ts
 * const result = await autoOptimize(srcDir, projectRoot);
 * console.log(formatAutoOptimizeResult(result));
 * // 输出:
 * // ═══════════════════════════════════════════════════
 * // 🚀 Auto-Optimization Report
 * // ═══════════════════════════════════════════════════
 * // 执行 1，成功 1，失败 0，回滚 0
 * //
 * //   ✅ 添加缺失的测试文件: 所有测试通过，优化成功
 * //      测试: 11/11
 * //      快照: 6e3a563b
 * // ```
 */
export function formatAutoOptimizeResult(r: AutoOptimizeResult): string {
  const lines = [
    "═══════════════════════════════════════════════════",
    "🚀 Auto-Optimization Report",
    "═══════════════════════════════════════════════════",
    r.summary,
    "",
  ];

  for (const e of r.executed) {
    lines.push(
      `  ${e.result.status === "success" ? "✅" : "❌"} ${e.proposal.target}: ${
        e.result.lesson
      }`
    );
    lines.push(
      `     测试: ${e.result.testSummary.passed}/${e.result.testSummary.total}`
    );
    if (e.gitSnapshot) {
      lines.push(`     快照: ${e.gitSnapshot.slice(0, 8)}`);
    }
  }

  if (r.skipped.length > 0) {
    lines.push("", "⏭️ 跳过:");
    for (const s of r.skipped) {
      lines.push(
        `  ${s.riskLevel === "medium" ? "🟡" : "🔴"} ${s.target}`
      );
    }
  }

  return lines.join("\n");
}
