/**
 * @file auto-optimizer.ts — 全自动优化编排器 (Phase 5)
 * @module core/self-opt/auto-optimizer
 */
import * as fs from "node:fs";
import * as path from "node:path";
import type { InspectionReport, ResearchReport, OptimizationProposal, OptimizationResult, OptimizationLogEntry, FileChange } from "./types.js";
import { generateProposals, generateFileChanges } from "./proposal-engine.js";
import { executeOptimization } from "./self-test-runner.js";
import { createSnapshot, revertToSnapshot, finalizeSnapshot, isInGitRepo } from "./git-snapshot.js";
import { generateFixDiff } from "./diff-generator.js";

const AUTO_RISK = ["low"] as const;

export function loadOptimizationLog(projectRoot: string): OptimizationLogEntry[] {
  const logPath = path.join(projectRoot, "OPTIMIZATION_LOG.md");
  if (!fs.existsSync(logPath)) return [];
  try {
    const content = fs.readFileSync(logPath, "utf-8");
    const blocks = content.match(/\{[\s\S]*?\}/g);
    if (!blocks) return [];
    const entries: OptimizationLogEntry[] = [];
    for (const b of blocks) { try { const e = JSON.parse(b); if (e.result && e.proposal) entries.push(e); } catch {} }
    return entries;
  } catch { return []; }
}

export function appendOptimizationLog(projectRoot: string, entry: OptimizationLogEntry): void {
  const logPath = path.join(projectRoot, "OPTIMIZATION_LOG.md");
  const record = `## ${new Date().toISOString()}\n\n\`\`\`json\n${JSON.stringify(entry, null, 2)}\n\`\`\`\n\n---\n\n`;
  if (!fs.existsSync(logPath)) {
    fs.writeFileSync(logPath, `# Optimization Log\n\n> Auto-generated by Mini Agent\n\n---\n\n${record}`, "utf-8");
  } else {
    fs.appendFileSync(logPath, record, "utf-8");
  }
}

interface ExecResult { proposal: OptimizationProposal; result: OptimizationResult; gitSnapshot?: string; reverted: boolean; }

async function applyChanges(changes: FileChange[], cwd: string): Promise<{ success: boolean; error?: string }> {
  try {
    for (const f of changes) {
      const full = path.isAbsolute(f.path) ? f.path : path.join(cwd, f.path);
      if (f.action === "create" || f.action === "modify") {
        const dir = path.dirname(full);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
        if (f.content) fs.writeFileSync(full, f.content, "utf-8");
      } else if (f.action === "delete" && fs.existsSync(full)) { fs.unlinkSync(full); }
    }
    return { success: true };
  } catch (e: any) { return { success: false, error: e?.message }; }
}

async function execProposal(p: OptimizationProposal, cwd: string, srcDir: string, useGit: boolean): Promise<ExecResult> {
  let snap: string | null = null;
  if (useGit) {
    console.log(`  📸 创建快照: ${p.target}`);
    snap = await createSnapshot(cwd, `pre-${p.target}`);
    if (snap) console.log(`  📸 ${snap.slice(0, 8)}`);
  }
  // 确保有文件变更
  if (p.files.length === 0) {
    const { inspectSelf } = await import("./inspector.js");
    const insp = await inspectSelf(srcDir);
    generateFileChanges(p, insp);
    // 如果还是没有，用 diff-generator 生成
    if (p.files.length === 0) {
      const fake = p.testCases.map(tc => ({ testCaseId: tc.id, passed: false, output: "待生成", durationMs: 0 }));
      const diff = await generateFixDiff(p, fake, srcDir);
      if (diff.success) p.files = diff.changes;
    }
  }
  const result = await executeOptimization(p, cwd, async () => applyChanges(p.files, cwd));
  if (useGit && snap) {
    if (result.status === "success") await finalizeSnapshot(cwd, snap, `[self-opt] ${p.target}`);
    else {
      const rv = await revertToSnapshot(cwd, snap);
      result.reverted = rv.success;
      if (rv.success) result.lesson += " [已回滚]"; else result.lesson += ` [回滚失败: ${rv.error}]`;
    }
  }
  return { proposal: p, result, gitSnapshot: snap ?? undefined, reverted: result.reverted };
}

export interface AutoOptimizeResult { inspection: InspectionReport; research: ResearchReport; proposals: OptimizationProposal[]; executed: ExecResult[]; skipped: OptimizationProposal[]; summary: string; }

export async function autoOptimize(srcDir: string, projectRoot: string): Promise<AutoOptimizeResult> {
  console.log("\n[1/5] 🔍 自我审视...");
  const { inspectSelf } = await import("./inspector.js");
  const insp = await inspectSelf(srcDir);
  console.log(`  架构: ${insp.architectureChecks.filter(c => c.passed).length}/${insp.architectureChecks.length}`);
  console.log(`  未测试模块: ${insp.moduleAnalysis.filter(m => !m.hasTests && m.linesOfCode > 50).length} 个`);

  console.log("\n[2/5] 🌐 外部调研...");
  const { researchExternal } = await import("./researcher.js");
  const res = await researchExternal();
  console.log(`  资源: ${res.references.length} 个`);

  console.log("\n[3/5] 📋 生成提案...");
  const proposals = generateProposals(insp, res);
  for (const p of proposals) generateFileChanges(p, insp);
  const auto = proposals.filter(p => AUTO_RISK.includes(p.riskLevel as "low"));
  const skipped = proposals.filter(p => !AUTO_RISK.includes(p.riskLevel as "low"));
  console.log(`  总计: ${proposals.length}, 自动: ${auto.length}, 跳过: ${skipped.length}`);

  const useGit = await isInGitRepo(projectRoot);
  const executed: ExecResult[] = [];
  for (let i = 0; i < auto.length; i++) {
    console.log(`\n[4/${auto.length}] 📌 执行: ${auto[i].target} (${auto[i].files.length} 文件变更)`);
    const r = await execProposal(auto[i], projectRoot, srcDir, useGit);
    executed.push(r);
    appendOptimizationLog(projectRoot, { result: r.result, proposal: { id: r.proposal.id, type: r.proposal.type, target: r.proposal.target, description: r.proposal.description, riskLevel: r.proposal.riskLevel } });
    console.log(`  ${r.result.status === "success" ? "✅" : "❌"} ${r.result.lesson}`);
    if (r.gitSnapshot) console.log(`  📸 快照: ${r.gitSnapshot.slice(0, 8)}`);
  }

  const ok = executed.filter(e => e.result.status === "success").length;
  const fail = executed.filter(e => e.result.status === "failed").length;
  const rv = executed.filter(e => e.result.reverted).length;
  const summary = `执行 ${executed.length}，成功 ${ok}，失败 ${fail}，回滚 ${rv}` + (skipped.length > 0 ? `，${skipped.length} 个跳过` : "");
  return { inspection: insp, research: res, proposals, executed, skipped, summary };
}

export function formatAutoOptimizeResult(r: AutoOptimizeResult): string {
  const lines = ["═══════════════════════════════════════════════════", "🚀 Auto-Optimization Report", "═══════════════════════════════════════════════════", r.summary, ""];
  for (const e of r.executed) {
    lines.push(`  ${e.result.status === "success" ? "✅" : "❌"} ${e.proposal.target}: ${e.result.lesson}`);
    lines.push(`     测试: ${e.result.testSummary.passed}/${e.result.testSummary.total}`);
    if (e.gitSnapshot) lines.push(`     快照: ${e.gitSnapshot.slice(0, 8)}`);
  }
  if (r.skipped.length > 0) { lines.push("", "⏭️ 跳过:"); for (const s of r.skipped) lines.push(`  ${s.riskLevel === "medium" ? "🟡" : "🔴"} ${s.target}`); }
  return lines.join("\n");
}
